M48
; DRILL file {KiCad 9.0.3} date 2026-09-01T23:47:08-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-01T23:47:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X166.0Y-106.11
X166.0Y-111.89
T2
X128.246Y-105.961
X128.246Y-113.961
M30
